from __future__ import annotations

from pathlib import Path
import shutil
from uuid import uuid4

from app.config import settings
from app.providers.image_provider import GeneratedImageFile


class MockImageProvider:
    name = "mock"
    capabilities = {"text_to_image", "image_to_image", "reference_image"}

    def generate_images(
        self,
        *,
        project_id: int,
        source_image_path: str | None,
        positive_prompt: str,
        negative_prompt: str,
        size: str,
        count: int,
    ) -> list[GeneratedImageFile]:
        project_dir = settings.generated_dir / str(project_id)
        project_dir.mkdir(parents=True, exist_ok=True)
        width, height = self._parse_size(size)
        files: list[GeneratedImageFile] = []
        source = Path(source_image_path) if source_image_path else None

        for index in range(count):
            if source and source.exists():
                suffix = source.suffix or ".png"
                target = project_dir / f"mock_{uuid4().hex}_{index + 1}{suffix}"
                shutil.copyfile(source, target)
            else:
                target = project_dir / f"mock_{uuid4().hex}_{index + 1}.svg"
                target.write_text(self._svg_placeholder(width, height, index), encoding="utf-8")
            files.append(
                GeneratedImageFile(
                    image_path=target,
                    image_url=f"/uploads/generated/{project_id}/{target.name}",
                    width=width,
                    height=height,
                )
            )
        return files

    def _parse_size(self, size: str) -> tuple[int, int]:
        if "x" not in size:
            return 1024, 1024
        left, right = size.lower().split("x", 1)
        return int(left), int(right)

    def _svg_placeholder(self, width: int, height: int, index: int) -> str:
        colors = [("#e7f8f3", "#13b89a"), ("#fff1e8", "#f97316"), ("#eef7ff", "#2563eb"), ("#f7f3ff", "#7c3aed")]
        bg, accent = colors[index % len(colors)]
        return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <rect width="100%" height="100%" rx="36" fill="{bg}"/>
  <circle cx="{width * 0.5}" cy="{height * 0.42}" r="{min(width, height) * 0.18}" fill="{accent}" opacity="0.16"/>
  <rect x="{width * 0.28}" y="{height * 0.28}" width="{width * 0.44}" height="{height * 0.34}" rx="28" fill="white" stroke="{accent}" stroke-width="8"/>
  <text x="50%" y="68%" text-anchor="middle" font-family="Arial, sans-serif" font-size="42" fill="#16352f">Mock Product Shot</text>
  <text x="50%" y="75%" text-anchor="middle" font-family="Arial, sans-serif" font-size="28" fill="#5f726d">Generated by ProductShot Agent</text>
</svg>"""
